version = "1.0"

[models]
wpl = "./rule/parse/wparse/wpl"
oml = "./rule/parse/wparse/oml"
sources = "./rule/parse/wparse/sources"
sinks = "./rule/parse/wparse/sinks"

[performance]
parse_workers = 2
rate_limit_rps = 0

[rescue]
path = "./data/rescue"

[log_conf]
level = "warn,ctrl=info,launch=info,klib=info"
output = "File"
[log_conf.file]
path = "./data/logs"

[stat]
window_sec = 60

[[stat.pick]]
key = "pick_stat"
target = "*"
fields = []
top_n = 20

[[stat.parse]]
key = "parse_stat"
target = "*"
fields = []
top_n = 20

[[stat.sink]]
key = "sink_stat"
target = "*"
fields = []
top_n = 20