version = "2.0"

[sink_group]
name = "all"
parallel =  ${WORK_CNT:6}
oml= ["/oml/static/*"]
[[sink_group.sinks]]
name = "main"
connect = "file_json_sink"
#connect = "fast_file_sink"
params = { file = "all.dat" }
